// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWrLi-YBisNUfxuw2_W4DwjK2pUUq8gjw',
    appId: '1:94245277378:web:0e9f762114099bdd8db55b',
    messagingSenderId: '94245277378',
    projectId: 'privaap-2fce9',
    authDomain: 'privaap-2fce9.firebaseapp.com',
    storageBucket: 'privaap-2fce9.appspot.com',
    measurementId: 'G-5J68YMXHM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH_3RICyXXHC-PVTXlooAU26ZIp0f1osI',
    appId: '1:94245277378:android:4dea5a4fc304a84c8db55b',
    messagingSenderId: '94245277378',
    projectId: 'privaap-2fce9',
    storageBucket: 'privaap-2fce9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfAQSJ7FsDQTZL8hM2Sj43J7MzF7QugI',
    appId: '1:94245277378:ios:8990312e2d3489b28db55b',
    messagingSenderId: '94245277378',
    projectId: 'privaap-2fce9',
    storageBucket: 'privaap-2fce9.appspot.com',
    androidClientId: '94245277378-h8oh3ibmcnq7ej568grpk7a7rhgu3423.apps.googleusercontent.com',
    iosClientId: '94245277378-psssc0rdls2s4lt2abjk600lo6j4ttn2.apps.googleusercontent.com',
    iosBundleId: 'com.comarca.privaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqfAQSJ7FsDQTZL8hM2Sj43J7MzF7QugI',
    appId: '1:94245277378:ios:8990312e2d3489b28db55b',
    messagingSenderId: '94245277378',
    projectId: 'privaap-2fce9',
    storageBucket: 'privaap-2fce9.appspot.com',
    androidClientId: '94245277378-h8oh3ibmcnq7ej568grpk7a7rhgu3423.apps.googleusercontent.com',
    iosClientId: '94245277378-psssc0rdls2s4lt2abjk600lo6j4ttn2.apps.googleusercontent.com',
    iosBundleId: 'com.comarca.privaap',
  );
}
